#!/usr/bin/env python3
"""
load_postgis.py - Create/refresh the osm_db PostGIS database from a local PBF file.
Expects a file matching greece-*.osm.pbf in the project root.
Download from: https://download.geofabrik.de/europe/greece.html
Run from create_osm directory:
    python load_postgis.py
"""
import glob
import os
import subprocess
import time
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]

_tags_df = pd.read_csv(PROJECT_ROOT / "w2v_columns.csv")
USEFUL_TAG_PAIRS: set[tuple[str, str]] = set()
for _col in _tags_df["column"]:
    _parts = _col.split("_", 1)
    if len(_parts) == 2:
        USEFUL_TAG_PAIRS.add((_parts[0], _parts[1]))

USEFUL_TAGS: set[str] = {k for k, v in USEFUL_TAG_PAIRS}

CREATEDB   = "createdb"
DROPDB     = "dropdb"
PSQL       = "psql"
OSM2PGSQL  = "osm2pgsql"
DB_USER    = "postgres"
DB_PASSWORD = "postgres"
DB_NAME    = "osm_db"

os.environ["PGPASSWORD"] = DB_PASSWORD


# ---------------------------------------------------------------------------
# Lua flex-output filter generator
# ---------------------------------------------------------------------------

def _build_allowed(tag_pairs: set) -> dict[str, list[str]]:
    """Collapse (key, value) pairs into {key: [value, ...]} for Lua emission."""
    allowed: dict[str, list[str]] = {}
    for k, v in tag_pairs:
        allowed.setdefault(k, []).append(v)
    return allowed


import json

def make_lua_filter(tag_pairs: set, polygon_features_path: Path) -> str:
    allowed = _build_allowed(tag_pairs)
    polygon_features = json.loads(polygon_features_path.read_text())

    lua_lines = [
        "-- Auto-generated by load_postgis.py -- do not edit by hand",
        "",
        "-- Allowed tag combinations (key -> set of values)",
        "local allowed_tags = {}",
    ]
    for key, values in sorted(allowed.items()):
        vals_lua = ", ".join(f'["{v}"]=true' for v in sorted(values))
        lua_lines.append(f'allowed_tags["{key}"] = {{ {vals_lua} }}')

    lua_lines += [
        "",
        "local function matches(tags)",
        "  for k, v in pairs(tags) do",
        "    if allowed_tags[k] and allowed_tags[k][v] then return true end",
        "  end",
        "  return false",
        "end",
        "",
        "local function filter_tags(tags)",
        "  local filtered = {}",
        "  for k, v in pairs(tags) do",
        "    if allowed_tags[k] and allowed_tags[k][v] then",
        "      filtered[k] = v",
        "    end",
        "  end",
        "  return filtered",
        "end",
        "",
        "-- Polygon decision tables (from polygon-features.json)",
        "local polygon_all       = {}",
        "local polygon_whitelist = {}",
        "local polygon_blacklist = {}",
    ]

    for rule in polygon_features:
        key    = rule["key"]
        mode   = rule["polygon"]
        values = rule.get("values", [])
        if mode == "all":
            lua_lines.append(f'polygon_all["{key}"] = true')
        elif mode == "whitelist":
            vals_lua = ", ".join(f'["{v}"]=true' for v in values)
            lua_lines.append(f'polygon_whitelist["{key}"] = {{ {vals_lua} }}')
        elif mode == "blacklist":
            vals_lua = ", ".join(f'["{v}"]=true' for v in values)
            lua_lines.append(f'polygon_blacklist["{key}"] = {{ {vals_lua} }}')

    lua_lines += [
        "",
        "local function is_polygon(tags)",
        "  for k, v in pairs(tags) do",
        "    if polygon_all[k] then return true end",
        "    if polygon_whitelist[k] and polygon_whitelist[k][v] then return true end",
        "    if polygon_blacklist[k] and not polygon_blacklist[k][v] then return true end",
        "  end",
        "  return false",
        "end",
        "",
        'local polygons = osm2pgsql.define_table({ name="planet_osm_polygon",',
        '  ids={ type="area", id_column="osm_id" },',
        '  columns={',
        '    { column="name", type="text"   },',
        '    { column="tags", type="hstore" },',
        '    { column="way",  type="geometry", projection=3857 },',
        '}})',
        'local lines = osm2pgsql.define_table({ name="planet_osm_line",',
        '  ids={ type="way", id_column="osm_id" },',
        '  columns={',
        '    { column="name", type="text"   },',
        '    { column="tags", type="hstore" },',
        '    { column="way",  type="geometry", projection=3857 },',
        '}})',
        'local points = osm2pgsql.define_table({ name="planet_osm_point",',
        '  ids={ type="node", id_column="osm_id" },',
        '  columns={',
        '    { column="name", type="text"   },',
        '    { column="tags", type="hstore" },',
        '    { column="way",  type="geometry", projection=3857 },',
        '}})',
        "",
        "function osm2pgsql.process_node(object)",
        "  if not matches(object.tags) then return end",
        "  points:insert({",
        "    name = object.tags.name,",
        "    tags = filter_tags(object.tags),",
        "    way  = object:as_point(),",
        "  })",
        "end",
        "",
        "function osm2pgsql.process_way(object)",
        "  if not matches(object.tags) then return end",
        "  if object.is_closed and is_polygon(object.tags) then",
        "    polygons:insert({",
        "      name = object.tags.name,",
        "      tags = filter_tags(object.tags),",
        "      way  = object:as_polygon(),",
        "    })",
        "  else",
        "    lines:insert({",
        "      name = object.tags.name,",
        "      tags = filter_tags(object.tags),",
        "      way  = object:as_linestring(),",
        "    })",
        "  end",
        "end",
        "",
        "function osm2pgsql.process_relation(object)",
        '  if object.tags.type ~= "multipolygon" then return end',
        "  if not matches(object.tags) then return end",
        "  polygons:insert({",
        "    name = object.tags.name,",
        "    tags = filter_tags(object.tags),",
        "    way  = object:as_multipolygon(),",
        "  })",
        "end",
    ]

    return "\n".join(lua_lines) + "\n"

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    start_time = time.time()

    # 1. Write Lua filter next to this script
    PROJECT_ROOT = Path(__file__).resolve().parents[1]
    polygon_features_path = PROJECT_ROOT / "polygon-features.json"
    lua_path = PROJECT_ROOT / "osm_filter.lua"
    if lua_path.exists():
        print(f"Lua filter already exists (skipping)")
    else:
        lua_path.write_text(make_lua_filter(USEFUL_TAG_PAIRS, polygon_features_path))
        print(f"Wrote Lua filter -> {lua_path}  "
            f"({len(_build_allowed(USEFUL_TAG_PAIRS))} tag keys)")

    # 2. Drop existing database
    try:
        subprocess.run(
            [DROPDB, "-U", DB_USER, "--if-exists", DB_NAME], check=True
        )
        print(f"Dropped database '{DB_NAME}'")
    except subprocess.CalledProcessError:
        print(f"Could not drop '{DB_NAME}', continuing...")

    # 3. Create fresh database
    subprocess.run([CREATEDB, "-U", DB_USER, DB_NAME], check=True)
    print(f"Created database '{DB_NAME}'")

    # 4. Enable PostGIS and hstore
    for ext in ("postgis", "hstore"):
        subprocess.run(
            [PSQL, "-U", DB_USER, "-d", DB_NAME,
             "-c", f"CREATE EXTENSION IF NOT EXISTS {ext};"],
            check=True,
        )
    print("Extensions enabled (postgis, hstore)")

    # 5. Import OSM files with flex output + our Lua filter
    osm_files = glob.glob(str(PROJECT_ROOT / "greece-*.osm.pbf"))
    if not osm_files:
        print(
            "No OSM .pbf files found in project root. "
            "Download from https://download.geofabrik.de/europe/greece.html"
        )
    else:
        print("Found OSM files:", osm_files)
        for f in osm_files:
            print(f"Importing {f} ...")
            subprocess.run(
                [
                    OSM2PGSQL,
                    "-U", DB_USER,
                    "-d", DB_NAME,
                    "--slim", "--drop",
                    "-O", "flex",
                    "-S", str(lua_path),
                    f,
                ],
                check=True,
            )
            print(f"Imported {f}")

    elapsed = time.time() - start_time
    print(f"Done. Total time: {elapsed:.2f}s")

    result = subprocess.run(
        [PSQL, "-U", DB_USER, "-d", DB_NAME, "-t", "-A", "-c",
        "SELECT pg_size_pretty(pg_database_size(current_database()));"],
        check=True, capture_output=True, text=True
    )
    print(f"💾 Database size: {result.stdout.strip()}")


if __name__ == "__main__":
    main()